[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/axios/**"]
  
[functions.generate-image]
  timeout = 30

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 